language: julia
julia:
  - 1

codecov: true

jobs:
  include:

    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("HRV")'
        - julia -e 'Pkg.test("HRV", coverage=true)'
        - julia --project=docs/ -e 'Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
